"""empty message

Revision ID: 1bf8669adecd
Revises: 8642578adb0d
Create Date: 2018-08-30 10:06:46.910540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf8669adecd'
down_revision = '8642578adb0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('publicity', sa.String(), nullable=True))
    op.add_column('label', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'type')
    op.drop_column('label', 'publicity')
    # ### end Alembic commands ###
