"""add tags table

Revision ID: 24326aaacd15
Revises: 
Create Date: 2018-08-20 18:42:08.639561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24326aaacd15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('originator', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['originator'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    # ### end Alembic commands ###
