"""empty message

Revision ID: 48c0aa4fd5e1
Revises: 62b076d36b1e
Create Date: 2018-08-23 17:19:09.827146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c0aa4fd5e1'
down_revision = '62b076d36b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('account_id', sa.Integer(), nullable=False))
    op.drop_column('account', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('account', 'account_id')
    # ### end Alembic commands ###
