"""empty message

Revision ID: 5182d7c7baf6
Revises: e71054ed7948
Create Date: 2018-08-23 16:23:41.225870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5182d7c7baf6'
down_revision = 'e71054ed7948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('account', 'account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('account_id', sa.INTEGER(), nullable=False))
    op.drop_column('account', 'id')
    # ### end Alembic commands ###
