"""empty message

Revision ID: 62b076d36b1e
Revises: 5182d7c7baf6
Create Date: 2018-08-23 16:36:26.908852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b076d36b1e'
down_revision = '5182d7c7baf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('photo_url', sa.String(), nullable=True))
    op.drop_column('person', 'picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('person', 'photo_url')
    # ### end Alembic commands ###
