"""empty message

Revision ID: 86a212c3a514
Revises: 1bf8669adecd
Create Date: 2018-10-22 16:22:05.495215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a212c3a514'
down_revision = '1bf8669adecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('label_text_key', 'label', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('label_text_key', 'label', ['text'])
    # ### end Alembic commands ###
