"""update tags and persons

Revision ID: b6bbbaa003d6
Revises: 33e86d952883
Create Date: 2018-08-21 11:38:48.184335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bbbaa003d6'
down_revision = '33e86d952883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('person', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('person', sa.Column('is_user', sa.Boolean(), nullable=True))
    op.add_column('person', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('person', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('tag', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('tag', sa.Column('publicity', sa.String(), nullable=True))
    op.add_column('tag', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('tag', sa.Column('subject', sa.Integer(), nullable=True))
    op.add_column('tag', sa.Column('type', sa.String(), nullable=True))
    op.add_column('tag', sa.Column('updated', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'tag', 'person', ['subject'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'updated')
    op.drop_column('tag', 'type')
    op.drop_column('tag', 'subject')
    op.drop_column('tag', 'slug')
    op.drop_column('tag', 'publicity')
    op.drop_column('tag', 'created')
    op.drop_column('person', 'updated')
    op.drop_column('person', 'last_name')
    op.drop_column('person', 'is_user')
    op.drop_column('person', 'first_name')
    op.drop_column('person', 'created')
    # ### end Alembic commands ###
