"""empty message

Revision ID: c61710bd09e7
Revises: 88382ad52028
Create Date: 2018-08-25 17:51:07.662884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c61710bd09e7'
down_revision = '88382ad52028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('account_id', sa.Integer(), nullable=False))
    op.drop_column('account', 'created')
    op.drop_column('account', 'id')
    op.drop_column('account', 'updated')
    op.drop_column('person', 'photo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('id', sa.INTEGER(), nullable=False))
    op.add_column('account', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('account', 'account_id')
    # ### end Alembic commands ###
