"""empty message

Revision ID: d0cf3e8adf08
Revises: 556f296952bc
Create Date: 2019-07-14 16:22:17.357126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0cf3e8adf08'
down_revision = '556f296952bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'account', 'person', ['person'], ['id'])
    op.create_foreign_key(None, 'tag', 'label', ['label'], ['id'])
    op.create_foreign_key(None, 'tag', 'person', ['originator'], ['id'])
    op.create_foreign_key(None, 'tag', 'person', ['subject'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_constraint(None, 'account', type_='foreignkey')
    # ### end Alembic commands ###
