"""empty message

Revision ID: dc92972df85c
Revises: 
Create Date: 2018-08-29 13:14:40.802646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc92972df85c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('connected_facebook', sa.Boolean(), nullable=True))
    op.add_column('account', sa.Column('connected_gmail', sa.Boolean(), nullable=True))
    op.add_column('account', sa.Column('connected_linkedin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'connected_linkedin')
    op.drop_column('account', 'connected_gmail')
    op.drop_column('account', 'connected_facebook')
    # ### end Alembic commands ###
