"""empty message

Revision ID: e71054ed7948
Revises: fbc39d6538a0
Create Date: 2018-08-23 16:21:23.173319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71054ed7948'
down_revision = 'fbc39d6538a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('account', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('person', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'picture')
    op.drop_column('account', 'updated')
    op.drop_column('account', 'created')
    # ### end Alembic commands ###
