"""empty message

Revision ID: f682d946b4de
Revises: 
Create Date: 2018-08-21 22:07:53.901874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f682d946b4de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('label', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tag', 'label', ['label'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'label')
    # ### end Alembic commands ###
