"""empty message

Revision ID: f80ce0a5b91b
Revises: 48c0aa4fd5e1
Create Date: 2018-08-23 17:31:07.130258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80ce0a5b91b'
down_revision = '48c0aa4fd5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('account', 'account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('account', 'id')
    # ### end Alembic commands ###
