"""empty message

Revision ID: fbc39d6538a0
Revises: f682d946b4de
Create Date: 2018-08-22 11:06:41.991630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc39d6538a0'
down_revision = 'f682d946b4de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('firebase_user_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('person', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person'], ['person.id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('firebase_user_id')
    )
    op.create_unique_constraint(None, 'label', ['text'])
    op.create_unique_constraint(None, 'label', ['slug'])
    op.create_unique_constraint(None, 'person', ['slug'])
    op.add_column('tag', sa.Column('originator_slug', sa.String(), nullable=True))
    op.add_column('tag', sa.Column('subject_slug', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tag', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_column('tag', 'subject_slug')
    op.drop_column('tag', 'originator_slug')
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'label', type_='unique')
    op.drop_constraint(None, 'label', type_='unique')
    op.drop_table('account')
    # ### end Alembic commands ###
